
package com.s11group2.profiling_database.View;

import javax.swing.*;
import java.time.LocalDate;
import com.s11group2.profiling_database.Controller.AppController;
import com.s11group2.profiling_database.Util.InputValidation;
/**
 *
 * @author migue
 */
public class InputPage extends JPanel {
    private AppController appController;
    /**
     * Creates new form InputPage
     */
    public InputPage() {
        initComponents();
        appController = new AppController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buildingNumberField = new javax.swing.JTextField();
        householdExpenditureField = new javax.swing.JTextField();
        unitNumberField = new javax.swing.JTextField();
        unitAmortizationField = new javax.swing.JTextField();
        yearOfResidenceField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        middleNameField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        birthdayField = new javax.swing.JTextField();
        civilStatusField = new javax.swing.JTextField();
        contactNumberField = new javax.swing.JTextField();
        educAttainmentField = new javax.swing.JTextField();
        occupationField = new javax.swing.JTextField();
        monthlyIncomeField = new javax.swing.JTextField();
        healthStatusField = new javax.swing.JTextField();
        pwdTypeField = new javax.swing.JTextField();
        submitNewHousehold = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 240, 214));

        jLabel2.setBackground(new java.awt.Color(255, 240, 214));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("ADD NEW HOUSEHOLD");

        buildingNumberField.setText("Building Number");
        buildingNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingNumberFieldActionPerformed(evt);
            }
        });

        householdExpenditureField.setText("Monthly Household Expenditure");
        householdExpenditureField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                householdExpenditureFieldActionPerformed(evt);
            }
        });

        unitNumberField.setText("Unit Number");
        unitNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitNumberFieldActionPerformed(evt);
            }
        });

        unitAmortizationField.setText("Monthly Unit Amortization");
        unitAmortizationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitAmortizationFieldActionPerformed(evt);
            }
        });

        yearOfResidenceField.setText("Year of Residence");
        yearOfResidenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearOfResidenceFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("MAIN RESPONDENT");

        lastNameField.setText("Last Name");
        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        middleNameField.setText("Middle Name");
        middleNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameFieldActionPerformed(evt);
            }
        });

        firstNameField.setText("First Name");
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        genderField.setText("Gender");
        genderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFieldActionPerformed(evt);
            }
        });

        birthdayField.setText("Birthday MM/DD/YYYY");
        birthdayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayFieldActionPerformed(evt);
            }
        });

        civilStatusField.setText("Civil Status");
        civilStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civilStatusFieldActionPerformed(evt);
            }
        });

        contactNumberField.setText("Contact Number");
        contactNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberFieldActionPerformed(evt);
            }
        });

        educAttainmentField.setText("Highest Educational Attainment");
        educAttainmentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educAttainmentFieldActionPerformed(evt);
            }
        });

        occupationField.setText("Occupation");
        occupationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationFieldActionPerformed(evt);
            }
        });

        monthlyIncomeField.setText("Monthly Income");
        monthlyIncomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyIncomeFieldActionPerformed(evt);
            }
        });

        healthStatusField.setText("Health Status");
        healthStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthStatusFieldActionPerformed(evt);
            }
        });

        pwdTypeField.setText("PWD Type");
        pwdTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdTypeFieldActionPerformed(evt);
            }
        });

        submitNewHousehold.setBackground(new java.awt.Color(87, 128, 77));
        submitNewHousehold.setForeground(new java.awt.Color(255, 255, 255));
        submitNewHousehold.setText("SUBMIT");
        submitNewHousehold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitNewHouseholdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buildingNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addComponent(unitNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(householdExpenditureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(unitAmortizationField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(59, 59, 59)
                                .addComponent(yearOfResidenceField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(birthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(civilStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(contactNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(educAttainmentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(occupationField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(monthlyIncomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(healthStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(pwdTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(365, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitNewHousehold, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildingNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(householdExpenditureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitAmortizationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearOfResidenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(civilStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(educAttainmentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(occupationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthlyIncomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(healthStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitNewHousehold, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buildingNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buildingNumberFieldActionPerformed

    private void householdExpenditureFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_householdExpenditureFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_householdExpenditureFieldActionPerformed

    private void unitNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitNumberFieldActionPerformed

    private void unitAmortizationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitAmortizationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitAmortizationFieldActionPerformed

    private void yearOfResidenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearOfResidenceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearOfResidenceFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void middleNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameFieldActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void genderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFieldActionPerformed

    private void birthdayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayFieldActionPerformed

    private void civilStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civilStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_civilStatusFieldActionPerformed

    private void contactNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberFieldActionPerformed

    private void educAttainmentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educAttainmentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_educAttainmentFieldActionPerformed

    private void occupationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationFieldActionPerformed

    private void monthlyIncomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyIncomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthlyIncomeFieldActionPerformed

    private void healthStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_healthStatusFieldActionPerformed

    private void pwdTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdTypeFieldActionPerformed

    private void submitNewHouseholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitNewHouseholdActionPerformed
         
        
        int buildingNum = Integer.parseInt(buildingNumberField.getText());
        int unitNum = Integer.parseInt(unitNumberField.getText());
        double monthlyExpenditure = Double.parseDouble(householdExpenditureField.getText());
        double monthlyAmortization = Double.parseDouble(unitAmortizationField.getText());
        int yearOfResidence = Integer.parseInt(yearOfResidenceField.getText());

        appController.insertHousehold(buildingNum, unitNum, monthlyExpenditure, monthlyAmortization, yearOfResidence);

        String lastName = lastNameField.getText();
        String firstName = firstNameField.getText();
        String middleName = middleNameField.getText();
        String gender = genderField.getText();
        LocalDate birthday = LocalDate.parse(birthdayField.getText()); 
        String healthStatus = healthStatusField.getText();
        String pwdType = pwdTypeField.getText();
        int isSeniorCitizen = InputValidation.isSeniorCitizen(InputValidation.calculateAge(birthday)); 
        String civilStatus = civilStatusField.getText();
        String contactNumber = contactNumberField.getText();
        String highestEducationalAttainment = educAttainmentField.getText();
        String occupation = occupationField.getText();
        double monthlyIncome = Double.parseDouble(monthlyIncomeField.getText());
        int isMainRespondent = 1; 

        appController.insertMember(lastName, firstName, middleName, gender, birthday, healthStatus, pwdType, isSeniorCitizen, 
                                   civilStatus, contactNumber, highestEducationalAttainment, occupation, monthlyIncome, 
                                   isMainRespondent, buildingNum, unitNum);
    }//GEN-LAST:event_submitNewHouseholdActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthdayField;
    private javax.swing.JTextField buildingNumberField;
    private javax.swing.JTextField civilStatusField;
    private javax.swing.JTextField contactNumberField;
    private javax.swing.JTextField educAttainmentField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField genderField;
    private javax.swing.JTextField healthStatusField;
    private javax.swing.JTextField householdExpenditureField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JTextField monthlyIncomeField;
    private javax.swing.JTextField occupationField;
    private javax.swing.JTextField pwdTypeField;
    private javax.swing.JButton submitNewHousehold;
    private javax.swing.JTextField unitAmortizationField;
    private javax.swing.JTextField unitNumberField;
    private javax.swing.JTextField yearOfResidenceField;
    // End of variables declaration//GEN-END:variables
}


